esi_lecture_client/connexion/urls.py
from django.urls import path
from . import views

app_name = 'connexion'
urlpatterns = [
    path('', views.connexion, name='connexion'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    ]

esi_lecture_client/esi_lecture_client/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('connexion/', include('connexion.urls')),
    path('livre/', include('livre.urls')),
    path('admin/', admin.site.urls),
]

esi_lecture_client/home/urls.py
from django.urls import path
from .views import HomeView

app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

esi_lecture_client/livre/urls.py
from django.urls import path
from . import views

app_name = 'livre'
urlpatterns = [
    path('', views.livre, name='livre'),
    path('like/<int:book_id>/', views.like_book, name='like'),
]

esi_lecture_client/connexion/models.py
from django.db import models

# Create your models here.

esi_lecture_client/home/models.py
from django.db import models

# Create your models here.

esi_lecture_client/livre/models.py
from django.db import models

# Create your models here.

esi_lecture_client/connexion/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
import xmlrpc.client
from django.conf import settings



def connexion(request):

    return render(request, 'connexion/connexion.html')


def login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
    
    if not username or not password:
        messages.error(request, 'Veuillez remplir tous les champs du formulaire.')
        return render(request, 'connexion/connexion.html')

    try:
        common = xmlrpc.client.ServerProxy('{}/xmlrpc/2/common'.format(settings.URL_ODOO))  

        uid = common.authenticate(settings.DB_ODOO, username, password, {})

        if uid is False:
            messages.error(request, 'Authentification échouée. Vérifiez votre login et/ou mot de passe.')
            return render(request, 'connexion/connexion.html')
        else:
            print(username, password)
            request.session['is_connected'] = True
            request.session['username'] = username
            request.session['password'] = password
            messages.success(request, 'Authentification réussie')

    except Exception as e:
        messages.error(request, 'Problème avec la connexion au serveur Odoo.')
        return render(request, 'connexion/connexion.html')
    

    return HttpResponseRedirect(reverse('home:home'))



def logout(request):

    request.session['is_connected'] = False

    return HttpResponseRedirect(reverse('home:home'))

# Create your views here.

esi_lecture_client/home/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "home/index.html"

esi_lecture_client/livre/views.py
from django.shortcuts import render, redirect
from django.conf import settings
import xmlrpc.client
from django.contrib import messages
import functools


def livre(request):
    if request.session['is_connected']:
        username = request.session['username']
        password = request.session['password']

        common = xmlrpc.client.ServerProxy('{}/xmlrpc/2/common'.format(settings.URL_ODOO))  
        models = xmlrpc.client.ServerProxy('{}/xmlrpc/2/object'.format(settings.URL_ODOO))
        uid = common.authenticate(settings.DB_ODOO, username, password, {})    


        search_domain = [[]]
        print(request.POST.get('book_name_search'))
        if request.POST.get('book_name_search') != None:
            search_domain = [[['name', 'ilike', request.POST.get('book_name_search')]]]

        search_options = {
            'fields': ['name', 'description', 'date_publication', 'nombre_page', 'likes_count', 'auteur_ids', 'liked_by_users', 'couverture_image'],
            'order': 'likes_count desc, name asc'
        }

        books = models.execute_kw(settings.DB_ODOO, uid, password, 'livre.livre', 'search_read', search_domain, search_options)

        books = sorted(books, key=functools.cmp_to_key(lambda x, y: (y['likes_count'] - x['likes_count']) or (x['name'] < y['name'])))

        authors = models.execute_kw(settings.DB_ODOO, uid, password, 'res.partner', 'search_read', [[('category_id', 'ilike', 'Auteur')], ['name']])
        for book in books:
            author_names = [author['name'] 
                            for author in authors 
                                if author['id'] in book['auteur_ids']]
            book['auteur_names'] = author_names

        for book in books:
            book['is_liked'] = False
            for liked_by_user in book['liked_by_users']:
                if uid == liked_by_user:
                    book['is_liked'] = True
                    break
               
        context = {
            'books': books,
            'search': request.POST.get('book_name_search'),
        }

        return render(request, 'livre/livre.html', context)
    else:
        messages.error(request, 'Authentification échouée. Vérifiez votre login et/ou mot de passe.')
        return redirect('connexion:odoo_login')


def like_book(request, book_id):
    if request.session['is_connected']:
        username = request.session['username']
        password = request.session['password']

        common = xmlrpc.client.ServerProxy('{}/xmlrpc/2/common'.format(settings.URL_ODOO))  
        models = xmlrpc.client.ServerProxy('{}/xmlrpc/2/object'.format(settings.URL_ODOO))

        uid = common.authenticate(settings.DB_ODOO, username, password, {})

        result = models.execute_kw(settings.DB_ODOO, uid, password, 'livre.livre', 'toggle_like', [int(book_id)])
        
        if result:
            messages.success(request, 'liké / déliké')
        else:
            messages.error(request, 'Erreur lors de la mise à jour des likes')

        return redirect('livre:livre') 

    else:
        messages.error(request, 'Vous devez être connecté.')
        return redirect('connexion:odoo_login')

esi_lecture_client/connexion/templates/connexion/connexion.html
{% extends "_base.html" %}

{% block title %}Connexion{% endblock title %}

{% block content %}
<section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
          <div class="card bg-dark text-white" style="border-radius: 1rem;">
            <div class="card-body p-5 text-center">
  
              <div class="mb-md-5 mt-md-4 pb-5">
  
                <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                <p class="text-white-50 mb-5">S'il vous plait, entrer votre nom d'utilisateur et votre mot de passe!</p>
  
                <form class="form-outline form-white mb-4" method="post" action="{% url 'connexion:login' %}">
                    {% csrf_token %}
                    
                    <div class="form-outline form-white mb-4">
                        <label class="form-label" for="username">Nom d'utilisateur :</label>
                        <input class="form-control form-control-lg" type="text" name="username" required>
                    </div>

                    <div class="form-outline form-white mb-4">
                        <label class="form-label" for="password">Mot de passe :</label>
                        <input class="form-control form-control-lg" type="password" name="password" required>
                    </div>

                    <button class="btn btn-outline-light btn-lg px-5" type="submit">Se connecter</button>
                </form>
                
              </div>
  
              <div>
                <p class="mb-0">Vous n'avez pas de compte? <a href="#!" class="text-white-50 fw-bold">Sign Up</a>
                </p>
              </div>
  
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

esi_lecture_client/home/templates/home/index.html
{% extends "_base.html" %}

{% block title %}ESI LECTURE{% endblock title %}

{% block content %}

{% if request.session.is_connected %}
    <div class="p-1 m-3 bg-light">
        <h1>Bievenue {{ request.session.username }} sur le site de gestion de livres d'ESI LECTURE</h1>
    </div>
    {% else %}
    <div class="p-1 m-3 bg-light">
        <h1>Bienvenue sur le site gestion de livres</h1>
    </div>
{% endif %}

{% endblock content %}

esi_lecture_client/livre/templates/livre/livre.html
{% extends "_base.html" %}

{% block content %}

<div class="d-flex flex-column gap-3">
    <h1>Liste des Livres</h1>
    <div>
        <form action="{% url 'livre:livre' %}" method="post">
            {% csrf_token %}
            <div class="input-group">
                <input type="search" id="book_name_search" name="book_name_search"
                    value="{% if search is not None %}{{ search }}{% endif %}" />
                <button class="btn btn-dark text-white" type="submit">Recherche</button>
            </div>
        </form>
    </div>
    {% if error %}
    <p>{{ error }}</p>
    {% else %}
        {% if not books %}
            {% if search is not None %}
            <p>Il n'y a aucun livre pour votre recherche "{{ search }}"</p>
            {% else %}
            <p>Il n'y a aucun livre dans le gestionnaire</p>
            {% endif %}
        {% else %}
        <div class="accordion" id="accordionExample">
            {% for book in books %}
            <div class="accordion-item">
                <h2 class="accordion-header" id="heading{{ book.id }}">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapse{{ book.id }}" aria-expanded="true" aria-controls="collapse{{ book.id }}">
                        {{ book.name }}
                    </button>
                </h2>
                <div id="collapse{{ book.id }}" class="accordion-collapse collapse" aria-labelledby="heading{{ book.id }}"
                    data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <div>
                            <h5>Description:</h5>
                            <div class="description" style="white-space: pre-line;">
                                {% autoescape off %}
                                {{ book.description | safe }}
                                {% endautoescape %}
                            </div>
                            <h5>Date de publication: </h5>
                            <p>{{ book.date_publication }}</p>
                            <h5>Nombre de pages: </h5>
                            <p>{{ book.nombre_page }}</p>
                        </div>
                        <div>
                            <form action="{% url 'livre:like' book.id %}" method="get">
                                {% csrf_token %}
                                {% if book.is_liked %}
                                <button class="btn btn-outline-danger" type="submit">
                                    <i class="fa fa-heart"></i>
                                    {{ book.likes_count }}
                                </button>
                                {% else %}
                                <button class="btn btn-outline-success" type="submit">
                                    <i class="fa fa-heart"></i>
                                    {{ book.likes_count }}
                                </button>
                                {% endif %}
                            </form>
                        </div>
                        <div>
                            <h5>Auteurs: </h5>
                            {% for author_name in book.auteur_names %}
                            <p>{{ author_name }}</p>
                            {% endfor %}
                        </div>
                        <div>
                            {% if book.couverture_image %}
                            <h5>Couverture: </h5>
                            <img src="data:image/jpeg;base64,{{ book.couverture_image }}" alt="Couverture du livre">
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    {% endif %}
</div>
{% endblock content%}

esi_lecture_client/templates/_base.html
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
</head>

<body class="d-flex flex-column min-vh-100">
    <main class="flex-fill flex-grow-1 ">
        <div class="p-2 bg-dark text-white text-center">
            <h1 class="display-1">ESI LECTURE</h1>
            <h2>Client - Gestionnaire de livre</h2>
        </div>

        <!-- <nav class="navbar navbar-expand-sm bg-secondary navbar-light"> -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand btn btn-outline-primary btn-custom" href="{% url 'home:home' %}">
                    <i class="fa fa-home"></i>
                </a>
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav gap-3 ml-auto">
                        {% if request.session.is_connected %}
                        <li class="nav-item">
                            <a class="nav-link btn btn-outline-primary btn-custom" href="{% url 'livre:livre' %}">
                                <i class="bi bi-book"></i>
                                Livre
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
                <div class="d-flex">
                    {% if request.session.is_connected %}
                    <a class="nav-link btn btn-outline-danger btn-custom" href="{% url 'connexion:logout' %}">
                        <i class="bi bi-box-arrow-left"></i>
                        Logout
                    </a>
                    {% else %}
                    <a class="nav-link btn btn-outline-success btn-custom" href="{% url 'connexion:connexion' %}">
                        <i class="bi bi-box-arrow-right"></i>
                        Login
                    </a>
                    {% endif %}
                </div>
            </div>
        </nav>
        <div class="container mt-5">
            {% block content %}{% endblock content %}
        </div>


        {% if messages %}
        {% for message in messages %}
        <div class="modal fade" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="messageModalLabel"
            aria-hidden="true">
            <div class="modal-dialog modal-bottom-end" role="document">
                <div class="modal-content">
                    <div class="modal-body">
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                        <div class="alert alert-success" role="alert">
                            {{ message }}
                        </div>
                        {% endif %}
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        <div class="alert alert-danger" role="alert">
                            {{ message }}
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </main>

    <footer class="p-2 bg-dark text-white">
        <nav class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item">
                <a href="{% url 'home:home' %}" class="nav-link px-2 text-body-secondary">Home</a>
            </li>
        </nav>
        <p class="text-center text-muted">G57618 & G56583</p>
    </footer>

    <style>
        .btn-custom {
            /* Ajoutez ici vos styles personnalisés */
            min-width: 120px;
            /* Par exemple, définissez une largeur minimale */
            /* Autres styles personnalisés si nécessaire */
        }
    </style>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var myModal = new bootstrap.Modal(document.getElementById('messageModal'));

            myModal.show();

            // Fermeture automatique après 5 secondes
            setTimeout(function () { myModal.hide(); }, 5000);
        });
    </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
        </script>


</body>

</html>